### PR TITLE
v1.0.0 release

### PR DESCRIPTION
**Pull request by danburzo**
### Code

Breaking changes:

* [x] Remove deprecated methods
* [ ] (Probably) make `xyz` refer to D65 XYZ instead of D50 XYZ ([ref](https://github.com/WICG/color-api/issues/24))
* [ ] (Probably) serialize `xyz` as `color(xyz)`

Outstanding issues:

* [ ] Sort out issues with spline interpolation (#50, #91, #94)

### Documentation

* [x] Prepare migration guide

### CODE REVIEW

**Comment by svgeesus** [comment]
> (Probably) serialize xyz as color(xyz)

That would seem consistent with [4.7.4. Serializing values of the color() function](https://drafts.csswg.org/css-color-4/#serializing-color-function-values)

**Comment by danburzo** [comment]
> That would seem consistent with 4.7.4. Serializing values of the color() function

Yes. Currently (as of `culori@0.20.0`) the two XYZs are serialized as `color(--xyz-d50)` and `color(--xyz-d65)` respectively.

**Comment by danburzo** [comment]
Decided to make a less ambitious `1.x` and leave the open issues for `2.x`.

**Comment by svgeesus** [comment]
https://github.com/w3c/csswg-drafts/issues/6722

**Pull request merged**
