### PR TITLE
Fix CommonJS module import

### PR DESCRIPTION
**Pull request by azat-io**
I am currently getting an error when using the culori module in CommonJS.

### CODE REVIEW

**Comment by danburzo** [comment]
Hi @azat-io, the `require()` endopoint is intentionally `culori/require`. This was introduced in the first major version (see the [Migration guide](https://culorijs.org/guides/migration/), _From v0.x to v1_), but is not documented in the _Getting started_ guide, so I understand how that’s not intuitive. 

The conditional export seems to be well supported by the Node versions we’re targeting, so it may be a good idea to just allow `require('culori');` at this point. Your proposed PR needs two changes:

* leave the `"./require"` import in place for backwards compatibility
* make the `".": { "import" }` export point to the source (like before) instead of the bundled MJS file

**Comment by azat-io** [comment]
@danburzo Fixed

**Comment by danburzo** [comment]
Thanks! Merged into `main`. I’ll not be able to publish a new release with this at the moment, since I’m preparing a major release on that branch. In the meantime, please use `require('culori/require');`.

**Comment by azat-io** [comment]
Thank you!
The problem was actually that `@types/culori` doesn't know anything about `/require`.
Hopefully there will be a release soon!

**Pull request merged**
